# Generated by Django 6.1.2 on 2026-10-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('memory_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('regular_price', models.CharField(blank=True, max_length=100, null=True)),
                ('promo_price', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=100, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('reviews_count', models.CharField(blank=True, max_length=100, null=True)),
                ('photos', models.JSONField(blank=True, default=list, null=True)),
                ('specifications', models.JSONField(blank=True, default=dict, null=True)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('parser_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, default='New', max_length=50, null=True)),
            ],
        ),
    ]
